Added support for LibMan and removed old banner images
aspnet/Templating pull request #679
Opened 2018-08-17 17:46 UTC by JustCallMeAD

Modified the starter template so that it supports LibMan by default. Also deleted the old banner images as they are not being used anymore.

2018-08-17 17:46 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/aspnet/Templating?pullRequest=679) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/aspnet/Templating?pullRequest=679) before we can accept your contribution.<br/><br/>:x: JustCallMeAD [sign now](https://cla.dotnetfoundation.org/aspnet/Templating?pullRequest=679)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/aspnet/Templating?pullRequest=679) it.</sub>

2018-08-17 17:58 UTC, JustCallMeAD commented
NOTE: Will need to make similar changes to the identity UI templates. I can do a pull request for these changes too if you would like me too?

2018-08-31 17:04 UTC, scottaddie commented on src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/libman.json
> +      "provider": "cdnjs",
You can remove the `provider` property from each of these object literals. The `defaultProvider` property will be used.

2018-08-31 17:05 UTC, scottaddie commented
@justcla You may be interested in this PR.

2018-09-05 22:44 UTC, Eilon commented
@mkArtakMSFT / @ryanbrandenburg - please check with @DamianEdwards on when/how we should get this in.

2018-09-12 23:10 UTC, ryanbrandenburg commented
[Seems like](https://github.com/aspnet/Templating/issues/471#event-1683852954) we're targeting LibMan for 3.0.0-preview1.

2018-10-11 19:38 UTC, ryanbrandenburg commented
Please rebase onto the latest from master. I ended up removing the banner images independently and making other changes in the mean time and there's a conflict in StarterWeb's _Layout.cshtml, so it will be much easier to see what's actually changing once this PR has the latest.

2018-10-17 19:54 UTC, ryanbrandenburg commented
@JustCallMeAD, a reminder to rebase this onto master so we can more easily see what the important changes are.

2018-10-19 19:25 UTC, ryanbrandenburg requested changes
I poked around at this locally and I think there are some extra things we'll want to address when doing this:

1. We should ensure that LibMan is installed, then run `libman restore` before the build step. A target similar to https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/Angular-CSharp.csproj.in#L40 would do the trick.
2. Let's not check the files that LibMan pulls down for us into Git anymore (they'll just get overridden anyway). That will break our baseline tests, so we'll have to update those and also confirm that all scenarios still work, integrity attributes still apply etc.

Since the LibMan work is scheduled for 3.0 (and we're still doing 2.2 work) either you can do those cleanup items or it'll be a bit of a wait before I can carve out some time. Either way this is a pretty good start and probably what we'll be looking to for #471.

2018-12-19 18:40 UTC, Eilon commented
Hi, we are closing this PR because the source code has all been moved to https://github.com/aspnet/AspNetCore/tree/master/src/Templating so that all the ASP.NET Core source code is in one place. If you are interested in continuing this contribution, we recommend you log a new issue in https://github.com/aspnet/AspNetCore/issues with details and if the proposal is accepted, send a new PR so the new repo. Sorry for any inconvenience!

2018-12-19 18:40 UTC, closed without merging